### ISSUE TITLE
opencv-python4.4.0.42出错

### ISSUE THREAD

**Issue by vitahlin** [MiniBullLab/easy_docker#4]
执行命令`pip3 install -r requirements_cuda10.0_ai.txt `，安装`opencv-python`依赖时出错：
```shell
Downloading https://files.pythonhosted.org/packages/77/f5/49f034f8d109efcf9b7e98fbc051878b83b2f02a1c73f92bbd37f317288e/opencv-python-4.4.0.42.tar.gz (88.9MB)
    100% |################################| 88.9MB 17kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zl9suf8a/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
```

**Comment by vitahlin** [comment]
需要升级`pip3`：`pip3 install --upgrade pip`
