### ISSUE TITLE
worksapce镜像初步测试

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_docker#44]
1.easy_sample_mark测试
2.easy_ai中classnet、denet、segnet测试
3.easy_ai中半精度训练

**Comment by foww-0001** [comment]
docker load正常，但是docker start发生错误，错误如下：
```
Group id=1000 name=wfw
User id=1000 name=wfw

Begin check EasyAI environment...
EasyAI environment OK

Starting docker container easy_runtime_wfw ...
access control disabled, clients can connect from any host
Unable to find image 'easy_runtime:latest' locally
docker: Error response from daemon: pull access denied for easy_runtime, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Failed to start docker container "easy_runtime_wfw" based on image: easy_runtime
```
@lpj0822 @vitahlin

**Comment by lpj0822** [comment]
启动脚本需要跟一个参数：./docker_start.sh workspace

**Comment by foww-0001** [comment]
运行启动命令后有报错：
```
Group id=1000 name=wfw
User id=1000 name=wfw

Begin check EasyAI environment...
EasyAI environment OK

Starting docker container easy_workspace_wfw ...
access control disabled, clients can connect from any host
e75641b4d88014865883860b82b3fe39144b56f306b2c798ef9e5992cfaa2eeb

Current user is not root, begin to create docker user...
Begin add group in image, id=1000 name=wfw
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "C.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Adding group `wfw' (GID 1000) ...
Done.
Add group in image success
Begin add user in image, id=wfw name=1000
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "C.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Adding user `wfw' ...
Adding new user `wfw' (1000) with group `wfw' ...
Creating home directory `/home/wfw' ...
Copying files from `/etc/skel' ...
Add user in image success
Create docker user success.

Begin start senseshield...
sudo: /usr/lib/senseshield/senseshield: command not found
Start senseshield failed.
```
@lpj0822 @vitahlin

**Comment by lpj0822** [comment]
http://118.31.19.101:8080/software/dongle/senseshield-2.3.0.45988-x86_64.deb
这个库要加到lib里面去
@vitahlin

**Comment by foww-0001** [comment]
如果不考虑加密狗软件，可以启动镜像吗
@lpj0822

**Comment by vitahlin** [comment]
跑错脚本了，develop分支docker目录start脚本

**Comment by foww-0001** [comment]
okay，运行docker里面的start和into脚本可以正常进入docker环境。

**Comment by lpj0822** [comment]
senseshield-2.3.0.45988-x86_64.deb这个库也需要加到lib里面，这个库在整理的时候弄忘了
@vitahlin

**Comment by foww-0001** [comment]
workspace上测试标注工具easy_sample_mark：
1. 测试了手动标注设置
2. 测试了2d框的标注
3. 测试了多边形的区域标注

**Comment by foww-0001** [comment]
workspace下测试denet转换出错，错误如下：
```
Traceback (most recent call last):
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/caffe/caffeparser.py", line 29, in <module>
    import io_nodes
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/caffe/io_nodes.py", line 26, in <module>
    import caffe_common as cfc
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/caffe/caffe_common.py", line 23, in <module>
    from caffe import Net
  File "/opt/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/opt/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libglog.so.0.3.5: cannot open shared object file: No such file or directory
```
@vitahlin @lpj0822

**Comment by lpj0822** [comment]
暂时关闭，后期重新建立issue
