### ISSUE TITLE
在docker下面运行ClassNET_tool.sh运行报错 

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_docker#68]
目前使用master分支下

```
process start...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/easy_tools/easy_ai.py", line 67, in <module>
    train_main()
  File "/usr/local/lib/python3.6/dist-packages/easy_tools/easy_ai.py", line 56, in train_main
    train_process.classify_model_train(dir_name)
  File "easy_tools/easyai_train.py", line 32, in easy_tools.easyai_train.EasyAiModelTrain.classify_model_train
  File "easyai/tools/sample/create_classify_sample.py", line 25, in easyai.tools.sample.create_classify_sample.CreateClassifySample.process_sample
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/easy_ai'
Failed to start easy_ai
```

**Comment by vitahlin** [comment]
这个程序在哪里，怎么执行 @lpj0822 @foww-0001

**Comment by vitahlin** [comment]
执行结果：
```shell
vitah@3b127ecb636f:/easy_data/easy_ai/easy_tools/train_scripts$ ./ClassNet.sh
/easy_ai/ImageSets/train.txt
/easy_ai/ImageSets/val.txt
Failed to start easy_ai
```

**Comment by foww-0001** [comment]
ClassNet数据位置: http://118.31.19.101:8080/dataset/cls/classnet_flower_2class.zip

**Comment by foww-0001** [comment]
运行./easy_tools/train_scripts/ClassNet.sh /path to train.txt /path to val.txt

**Comment by kingwangxiang** [comment]
develop合并到master分支

**Comment by vitahlin** [comment]
错误内容：
```shell
vitah@9df87a9a06e5:/easy_data/easy_ai/scripts/easy_tools$ ./ClassNet.sh /easy_data/classnet_flower_2class/ImageSets/train.txt /easy_data/classnet_flower_2class/ImageSets/val.txt
Failed to start easy_ai
```

这个是不是要先启动 @lpj0822

**Comment by vitahlin** [comment]
在easy_data的easy_ai目录下启动
```shell
vitah@9df87a9a06e5:/easy_data/easy_ai$ ./easy_tools/train_scripts/ClassNet.sh
/easy_ai/ImageSets/train.txt
/easy_ai/ImageSets/val.txt
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/easy_data/easy_ai/easy_tools/easy_ai.py", line 12, in <module>
    from easy_tools.model_train.ai_train import EasyAiModelTrain
  File "/easy_data/easy_ai/easy_tools/model_train/ai_train.py", line 8, in <module>
    from easyai.tools.utility.copy_image import CopyImage
  File "/easy_data/easy_ai/easyai/tools/__init__.py", line 1, in <module>
    from . import offline_test
  File "/easy_data/easy_ai/easyai/tools/offline_test/__init__.py", line 1, in <module>
    from . import offline_classify_evaluation
  File "/easy_data/easy_ai/easyai/tools/offline_test/offline_classify_evaluation.py", line 6, in <module>
    from easyai.tools.offline_test.base_offline_evaluation import BaseOfflineEvaluation
  File "/easy_data/easy_ai/easyai/tools/offline_test/base_offline_evaluation.py", line 6, in <module>
    from easyai.evaluation.utility.evaluation_factory import EvaluationFactory
  File "/easy_data/easy_ai/easyai/evaluation/__init__.py", line 2, in <module>
    from . import det2d
  File "/easy_data/easy_ai/easyai/evaluation/det2d/__init__.py", line 1, in <module>
    from . import detection_mAP
  File "/easy_data/easy_ai/easyai/evaluation/det2d/detection_mAP.py", line 10, in <module>
    from easyai.data_loader.det2d.det2d_sample import DetectionSample
  File "/easy_data/easy_ai/easyai/data_loader/__init__.py", line 7, in <module>
    from . import rec_text
  File "/easy_data/easy_ai/easyai/data_loader/rec_text/__init__.py", line 1, in <module>
    from . import rec_text_dataset
  File "/easy_data/easy_ai/easyai/data_loader/rec_text/rec_text_dataset.py", line 6, in <module>
    from easyai.data_loader.rec_text.rec_text_sample import RecTextSample
  File "/easy_data/easy_ai/easyai/data_loader/rec_text/rec_text_sample.py", line 5, in <module>
    import lmdb
ModuleNotFoundError: No module named 'lmdb'
Failed to start easy_ai
```

**Comment by lpj0822** [comment]
使用master分支代码

**Comment by vitahlin** [comment]
https://github.com/MiniBullLab/easy_ai/blob/main/easy_tools/train_scripts/ClassNET_tool.sh

**Comment by vitahlin** [comment]
`./easy_tools/train_scripts/ClassNET_tool.sh /easy_data/classnet_flower_2class/ImageSets/train.txt /easy_data/classnet_flower_2class/ImageSets/val.txt`

**Comment by vitahlin** [comment]
重试未出现类似问题
